auth_enabled: false

common:
  replication_factor: 1
  path_prefix: /loki/
  ring:
    kvstore:
      store: inmemory

server:
  http_listen_port: 3100
  log_level: info

storage_config:
  filesystem:
    directory: /loki/chunks

schema_config:
  configs:
    - store: tsdb
      from: "2024-01-01"
      object_store: filesystem
      schema: v13
      index:
        prefix: logs_
        period: 24h

# Prevent sending statistics to Grafana Labs (https://stats.grafana.org)
analytics:
  reporting_enabled: false
